name: Sync

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
          source-repo: git@github.com:doocs/jvm.git
          destination-repo: git@gitee.com:Doocs/jvm.git

    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
          gitee-username: yanglbme
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: doocs/jvm
          branch: main
